export const COLORS = [
  { name: 'Apricot', hex: '#ffd9b3' },
  { name: 'Black', hex: '#000000' },
  { name: 'Blue', hex: '#0066cc' },
  { name: 'Blue Green', hex: '#009999' },
  { name: 'Blue Violet', hex: '#6600cc' },
  { name: 'Brown', hex: '#993300' },
  { name: 'Carnation Pink', hex: '#ff99cc' },
  { name: 'Cerulean', hex: '#0099cc' },
  { name: 'Dandelion', hex: '#ffcc33' },
  { name: 'Gray', hex: '#999999' },
  { name: 'Green', hex: '#009900' },
  { name: 'Green Yellow', hex: '#99cc00' },
  { name: 'Indigo', hex: '#330099' },
  { name: 'Orange', hex: '#ff6600' },
  { name: 'Red', hex: '#ff0000' },
  { name: 'Red Orange', hex: '#ff3300' },
  { name: 'Red Violet', hex: '#cc0066' },
  { name: 'Scarlet', hex: '#ff2400' },
  { name: 'Violet', hex: '#9900cc' },
  { name: 'Violet Red', hex: '#cc0033' },
  { name: 'White', hex: '#ffffff' },
  { name: 'Yellow', hex: '#ffff00' },
  { name: 'Yellow Green', hex: '#99ff00' },
  { name: 'Yellow Orange', hex: '#ffcc00' }
];